"env.CMD_LAST_EXEC" = "2021-10-02T22:13:44.562023918+00:00"
path = ["/Users/florent/.rbenv/shims", "/Users/florent/.cargo/bin", "/usr/local/bin", "/usr/bin", "/bin", "/usr/sbin", "/sbin", "/usr/local/MacGPG2/bin", "/usr/local/share/dotnet", "/opt/X11/bin", "/Applications/Server.app/Contents/ServerRoot/usr/bin", "/Applications/Server.app/Contents/ServerRoot/usr/sbin", "/Library/Apple/usr/bin", "/Library/Frameworks/Mono.framework/Versions/Current/Commands", "/usr/local/git/bin", "/Users/florent/n/bin", "/Users/florent/.fzf/bin"]
prompt = "starship_prompt"
skip_welcome_message = "true"
startup = ["source ~/.config/.init.nu", "from_toml ~/.config/nu.env.toml | load-env"]
table_mode = "light"

[env]
CMD_DURATION_MS = "20134"
DISPLAY = "/private/tmp/com.apple.launchd.ZMYCKfAPD9/org.macosforge.xquartz:0"
HOME = "/Users/florent"
LANG = "en_CA.UTF-8"
LOGNAME = "florent"
N_PREFIX = "/Users/florent/n"
RBENV_SHELL = "zsh"
SHELL = "/usr/local/bin/nu"
SSH_AUTH_SOCK = "/private/tmp/com.apple.launchd.sYHPejusuF/Listeners"
TERM = "screen-256color"
TERM_PROGRAM = "tmux"
TERM_PROGRAM_VERSION = "3.2a"
TERM_SESSION_ID = "880C57DF-FAC3-4E0A-8E01-85D45C38618D"
TMPDIR = "/var/folders/0r/snw_mtd52zdfgtjt__jyhpg00000gn/T/"
TMUX = "/private/tmp/tmux-501/default,1649,3"
TMUX_PLUGIN_MANAGER_PATH = "/Users/florent/.tmux/plugins/"
USER = "florent"
XPC_FLAGS = "0x0"
XPC_SERVICE_NAME = "0"
_ = "/usr/local/bin/nu"
__CFBundleIdentifier = "com.apple.Terminal"
__CF_USER_TEXT_ENCODING = "0x1F5:0x0:0x0"

[line_editor]
history_duplicates = true
