path = ["/Users/florent/.rbenv/shims", "/Users/florent/.cargo/bin", "/usr/local/bin", "/usr/bin", "/bin", "/usr/sbin", "/sbin", "/usr/local/MacGPG2/bin", "/usr/local/share/dotnet", "/opt/X11/bin", "/Applications/Server.app/Contents/ServerRoot/usr/bin", "/Applications/Server.app/Contents/ServerRoot/usr/sbin", "/Library/Apple/usr/bin", "/Library/Frameworks/Mono.framework/Versions/Current/Commands", "/usr/local/git/bin", "/Users/florent/n/bin", "/Users/florent/.fzf/bin"]
prompt = "starship_prompt"
startup = ["source ~/.config/.init.nu"]
table_mode = "basic"

[env]
CMD_DURATION_MS = "0"
DISPLAY = "/private/tmp/com.apple.launchd.ZMYCKfAPD9/org.macosforge.xquartz:0"
HOME = "/Users/florent"
LANG = "en_CA.UTF-8"
LOGNAME = "florent"
MAKEFLAGS = ""
MAKELEVEL = "1"
MFLAGS = ""
N_PREFIX = "/Users/florent/n"
PWD = "/Users/florent/src/dotfiles"
RBENV_SHELL = "zsh"
SHELL = "/usr/local/bin/nu"
SHLVL = "5"
SSH_AUTH_SOCK = "/private/tmp/com.apple.launchd.sYHPejusuF/Listeners"
TERM = "screen-256color"
TERM_PROGRAM = "tmux"
TERM_PROGRAM_VERSION = "3.2a"
TERM_SESSION_ID = "880C57DF-FAC3-4E0A-8E01-85D45C38618D"
TMPDIR = "/var/folders/0r/snw_mtd52zdfgtjt__jyhpg00000gn/T/"
TMUX = "/private/tmp/tmux-501/default,1649,3"
TMUX_PANE = "%7"
TMUX_PLUGIN_MANAGER_PATH = "/Users/florent/.tmux/plugins/"
USER = "florent"
XPC_FLAGS = "0x0"
XPC_SERVICE_NAME = "0"
_ = "/usr/local/bin/nu"
__CFBundleIdentifier = "com.apple.Terminal"
__CF_USER_TEXT_ENCODING = "0x1F5:0x0:0x0"
starship_precmd_user_func = "blastoff"
