on: push
jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          rm /usr/local/bin/aws
          rm /usr/local/bin/aws*
          rm /usr/local/bin/go
          make
